# Generated by Django 4.1.1 on 2023-01-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=20)),
                ('customer_email', models.CharField(max_length=20)),
                ('address', models.CharField(default='', max_length=20)),
                ('gender', models.CharField(max_length=50)),
                ('cust_phone', models.BigIntegerField()),
                ('cust_pass', models.CharField(max_length=8)),
            ],
        ),
    ]
