# Generated by Django 4.1.1 on 2023-01-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_email',
            field=models.CharField(max_length=30),
        ),
    ]
